[package]
name = "miden-protocol"
version = "0.15.0"

[lib]
namespace = "miden::protocol"
path = "mod.masm"

[profile.release]
# Always produce debug information, as it can be stripped later by the VM
debug = true
# Use workspace-relative file paths in debug info for portability
trim_paths = true
